Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2019-11, with the labels that each got.

#57 [ios] Fix ornaments' view constraints bug in bold-text mode
  platform/ios/CHANGELOG.md
  platform/ios/src/MGLMapView.mm
Labels: ios

#72 Bump Xcode 11 builds to 11.2.1
  circle.yml
Labels: build

#73 Add timeout for ios-release-tag
  circle.yml
Labels: build

#74 Removes extraneous tab character in circle config
  circle.yml
Labels: build

#75 Fix unbound variable error
  platform/ios/scripts/publish.sh
Labels: build

#64 Adds tests for host check change.
  platform/darwin/test/MGLResourceTests.mm
Labels: tests

#76 Fix variable in publish script
  platform/ios/scripts/publish.sh
Labels: build

#70 Move common configuration settings into shared xcconfig
  platform/ios/app/MBXViewController.m
  platform/ios/common.xcconfig
  platform/ios/ios.xcodeproj/project.pbxproj
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/CI.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/Integration Test Harness.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/bench.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic+static.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/dynamic.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/iosapp.xcscheme
  platform/ios/ios.xcodeproj/xcshareddata/xcschemes/static.xcscheme
Labels: build
