Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2020-03, with the labels that each got.

#203 Add pr template for drafting changelogs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip changelog

#208 Add options for constraining the camera’s pitch
  platform/ios/CHANGELOG.md
  platform/ios/src/MGLMapView.h
  platform/ios/src/MGLMapView.mm
  platform/macos/CHANGELOG.md
  platform/macos/src/MGLMapView.h
  platform/macos/src/MGLMapView.mm
Labels: enhancement, ios, macOS

#188 Add async completion handler to MGLOfflineStorage::preloadData
  platform/darwin/src/MGLOfflineStorage.h
  platform/darwin/src/MGLOfflineStorage.mm
  platform/darwin/test/MGLOfflineStorageTests.mm
  platform/ios/CHANGELOG.md
  platform/macos/CHANGELOG.md
Labels: ios, macOS

#221 Reduce MapboxMobileEvents link time
  Makefile
Labels: build, ios

#226 Mapbox Maps SDK for iOS v5.8.0-beta.1, macOS v0.15.0-beta.1
  platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
  platform/ios/Mapbox-iOS-SDK-stripped.podspec
  platform/ios/Mapbox-iOS-SDK.podspec
  platform/macos/Mapbox-macOS-SDK-symbols.podspec
  platform/macos/Mapbox-macOS-SDK.podspec
Labels: build, ios, macOS

#229 Updates metrics trigger.
  circle.yml
Labels: build, skip changelog

#230 Fix for previous PR #229
  circle.yml
Labels: build, skip changelog

#231 Refactor metrics triggering
  circle.yml
Labels: skip changelog

#228 Adds NSURLSession delegate to MGLNetworkConfiguration
  platform/darwin/src/MGLNetworkConfiguration.h
  platform/darwin/src/MGLNetworkConfiguration.m
  platform/darwin/src/MGLNetworkConfiguration_Private.h
  platform/darwin/src/MGLNetworkIntegrationManager.h
  platform/darwin/src/MGLNetworkIntegrationManager.m
  platform/darwin/src/MGLOfflineStorage.mm
  platform/ios/Integration Tests/MGLIntegrationTestCase.h
  platform/ios/Integration Tests/MGLIntegrationTestCase.m
  platform/ios/Integration Tests/MGLMapViewIntegrationTest.h
  platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
  platform/ios/Integration Tests/MGLNetworkConfigurationIntegrationTests.mm
  platform/ios/ios.xcodeproj/project.pbxproj
  platform/ios/src/MGLMapView.mm
  platform/macos/macos.xcodeproj/project.pbxproj
  platform/macos/src/MGLMapView.mm
Labels: :warning: DO NOT MERGE, enhancement, skip changelog

#245 Fix compilation warnings when compiling tests in release.
  platform/darwin/test/MGLTestAssertionHandler.m
  platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.mm
  platform/ios/Integration Tests/MGLMapViewPendingBlockTests.m
Labels: skip changelog, tests
