Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2020-01, with the labels that each got.

#127 Updated SDK checker release URL
  platform/ios/src/MGLSDKUpdateChecker.mm
Labels: bug, documentation

#108 Introduce limited axis scrolling
  platform/ios/CHANGELOG.md
  platform/ios/src/MGLMapView.h
  platform/ios/src/MGLMapView.mm
Labels: enhancement

#152 Update podspecs and changelog for v5.7.0-beta.1
  platform/ios/CHANGELOG.md
  platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
  platform/ios/Mapbox-iOS-SDK-stripped.podspec
  platform/ios/Mapbox-iOS-SDK.podspec
Labels: ios
