Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2020-07, with the labels that each got.

#332 Add points.geojson file to the Integration Test Harness
  platform/ios/ios.xcodeproj/project.pbxproj
Labels: bug

#268 [ios] add allowScrollGesturesDuringRotateOrZoom
  platform/ios/CHANGELOG.md
  platform/ios/src/MGLMapView.h
  platform/ios/src/MGLMapView.mm
Labels: status: triage

#311 fix crash on nil completion
  platform/macos/src/MGLMapView.mm
Labels: bug, macOS

#336 Add accessiblePlaceSourceIdentifiers to make layers available to VoiceOver
  platform/darwin/src/MGLStyle.h
  platform/darwin/src/MGLStyle.mm
  platform/ios/CHANGELOG.md
  platform/ios/src/MGLMapAccessibilityElement.mm
  platform/ios/src/MGLMapView.mm
Labels: bug

#349 [ios] Add Xcode 11.6.0, 12.0 to nightly jobs.
  circle.yml
  platform/darwin/test/MGLOfflinePackTests.mm
  platform/ios/test/MGLMapViewLayoutTests.m
  platform/ios/test/MGLNetworkConfigurationTests.m
Labels: build

#352 Fixes for CircleCI build failures (and reporting)
  Makefile
  circle.yml
  xcode-beta-3-build-fix.xcconfig
Labels: build
