Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2020-11, with the labels that each got.

#537 Update gl-native to 5.2.1
  Cartfile
  Cartfile.resolved
  platform/ios/CHANGELOG.md
  platform/ios/Integration Test Harness/Info.plist
  platform/ios/Integration Tests/Info.plist
  platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
  platform/ios/Mapbox-iOS-SDK-stripped.podspec
  platform/ios/Mapbox-iOS-SDK.podspec
  platform/ios/app/Info.plist
  platform/ios/benchmark/Info.plist
  platform/ios/framework/Info-static.plist
  platform/ios/framework/Info.plist
  platform/ios/ios.xcodeproj/project.pbxproj
  platform/ios/test/Info.plist
Labels: build

#539 Updates version number to 6.3.0, bumps gl-native to 5.2.1 (#537)
  Cartfile
  Cartfile.resolved
  platform/ios/CHANGELOG.md
  platform/ios/Integration Test Harness/Info.plist
  platform/ios/Integration Tests/Info.plist
  platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
  platform/ios/Mapbox-iOS-SDK-stripped.podspec
  platform/ios/Mapbox-iOS-SDK.podspec
  platform/ios/app/Info.plist
  platform/ios/benchmark/Info.plist
  platform/ios/framework/Info-static.plist
  platform/ios/framework/Info.plist
  platform/ios/ios.xcodeproj/project.pbxproj
  platform/ios/test/Info.plist
Labels: build

#541 Updates podspecs' events dependency
  platform/ios/Mapbox-iOS-SDK-snapshot-dynamic.podspec
  platform/ios/Mapbox-iOS-SDK-stripped.podspec
  platform/ios/Mapbox-iOS-SDK.podspec
Labels: build

#544 Update release notes doc path
  platform/ios/scripts/release-notes-github.md.ejs
Labels: build, documentation

#345 [macos] Update changelog with entry from #311
  platform/macos/CHANGELOG.md
Labels: macOS

#549 Refine Apple Silicon / CocoaPods workaround
  platform/ios/CHANGELOG.md
  platform/ios/Mapbox-iOS-SDK.podspec
Labels: build

#560 Refine Apple Silicon / CocoaPods workaround (apfelsaft)
  platform/ios/CHANGELOG.md
  platform/ios/Mapbox-iOS-SDK.podspec
Labels: build, dependencies
