Repository mapbox/mapbox-gl-native-ios, pull requests merged in 2020-02, with the labels that each got.

#159 Add property to show whether the snapshotter logo is displayed.
  platform/darwin/src/MGLMapSnapshotter.mm
  platform/ios/src/MGLMapView.h
Labels: :warning: DO NOT MERGE

#170 Tweaks for failing integration tests on simulators
  platform/ios/Integration Tests/Annotation Tests/MGLAnnotationViewIntegrationTests.mm
  platform/ios/Integration Tests/MGLMapViewIntegrationTest.m
  platform/ios/ios.xcodeproj/project.pbxproj
Labels: tests

#173 Update label languages for Mapbox Streets v8.3
  platform/darwin/src/MGLVectorTileSource.mm
  platform/darwin/test/MGLStyleTests.mm
  platform/ios/CHANGELOG.md
  platform/macos/CHANGELOG.md
Labels: enhancement, localization
